### ISSUE TITLE
How to use with futures Stream of Vec<u8> values?

### ISSUE THREAD

**Issue by xrl** [rust-lang/flate2-rs#162]
I am trying to stream gzipped data from an S3 object in to a flate2 decompressor but the S3 library does not return a Read, just a futures Stream<Item=Vec<u8>, ...>. You can see the S3 library code related to the stream here: https://github.com/rusoto/rusoto/blob/master/rusoto/services/s3/src/generated.rs#L1092-L1131

Looks like users of the S3 library are finding similar flavors of the issue: https://github.com/rusoto/rusoto/issues/1070 .

Any chance this can be solved by an incantation of flate2?

**Comment by alexcrichton** [comment]
Thanks for the report! What you'll probably want to do is to transform the `Stream<Item=Vec...>` to a `AsyncRead` and then use that with this crate, although this crate doesn't provide a combinator for that.

**Comment by xrl** [comment]
@alexcrichto I am not familiar with AsyncRead, looks like it is part of futures-io 0.3? Rusoto is on `futures = "0.1.16"`. Any tips on resolving between the two?

**Comment by alexcrichton** [comment]
It's also part of the [futures 0.1 release (in Tokio)](https://docs.rs/tokio-io/0.1/tokio_io/trait.AsyncRead.html), and it's the async equivalent of `io::Read`

**Comment by joshtriplett** [comment]
I don't think this issue needs further action at this point. Please feel free to open a new issue if needed.
