### ISSUE TITLE
`GzDecoder` doesn't implement BufRead

### ISSUE THREAD

**Issue by zslayton** [rust-lang/flate2-rs#175]
Hello! The [docs for the `GzDecoder` struct](https://docs.rs/flate2/1.0.5/flate2/bufread/struct.GzDecoder.html) say:

> This structure exposes a `ReadBuf` [sic] interface that will consume compressed data from the underlying reader and emit uncompressed data.

If I've understood correctly, that would suggest that `GzDecoder` is intended to implement `BufRead`, which it currently doesn't. (Or maybe it's referencing the fact that GzDecoder wraps an `R: BufRead`, in which case the phrasing just needs to be tweaked?)

**Comment by alexcrichton** [comment]
Oh oops I think this is just a mistake, while this may have been intended oh-so-long-ago I think nowadays it's not as easily implementable and not available in the base library. This should probably just be a bug to tweak the docs and update the to remove this clause!

**Comment by joshtriplett** [comment]
Fixed in https://github.com/rust-lang/flate2-rs/commit/2a6dc3b66fe4313da1a58ebf6b4442998a39b841 . Will be in the next release.
