### ISSUE TITLE
Port the "tokio-io" feature to tokio 0.2.x

### ISSUE THREAD

**Issue by fisherdarling** [rust-lang/flate2-rs#211]
We have a use case that requires tokio 0.2.x `AsyncRead` and `AsyncWrite` and are currently working on a PR that upgrades tokio.

**Comment by fisherdarling** [comment]
@alexcrichton I've run into an issue with porting to `tokio 0.2`. Thing like `tokio::net::TcpStream` do not implement `std::io::Read` anymore, they only implement `AsyncRead`. `AsyncRead` is also not constrained by `Read` anymore.

This means you cannot create a `read::ZlibDecoder<TcpStreamReadHalf>` anymore with `tokio 0.2` types. I'm a little stuck with how I should continue. I've gotten what I think are working `AsyncRead` and `AsyncWrite` impls for the different types. You can look at the progress I've made on that front here: https://github.com/fisherdarling/flate2-rs/tree/tokio2

Thanks for any help

**Comment by gliderkite** [comment]
Is there any update for this @fisherdarling? Thanks!

**Comment by fisherdarling** [comment]
@gilderkite I'm actually thinking of closing this. Until there's a stable, Rust-wide idea of what `AsyncRead` and `AsyncWrite` looks like, I think it's better to just use the [async-compression](https://github.com/Nemo157/async-compression) adapters.
