### ISSUE TITLE
Using the flate2 crate with only AsyncRead/AsyncWrite

### ISSUE THREAD

**Issue by TheNeikos** [rust-lang/flate2-rs#268]
Hello! I'm trying to use a tcp `OwnedWriteHalf`  from tokio with flate2, but am unable to do so as it does not implement `Write` and instead only implements `AsyncWrite`.

Is there a way for me to still use this library? Since `GzEncoder` etc... all require `Write` but also implement `AsyncWrite` when the wrapped `T` does, it feels like that the `Write` bound is too restrictive.

Simple playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b0c9dd53d0735d38f24e076a1469c9e0

**Comment by gkelly** [comment]
I think this comes from using the older `AsyncRead`/`AsyncWrite` definitions from `tokio-io`. In that crate they were extensions of `Read`/`Write`. But in more recent tokio they are not.

**Comment by TheNeikos** [comment]
Ah, indeed in 2.0 it seems that the `Write` [bound has been removed](https://docs.rs/tokio-io/0.2.0-alpha.6/tokio_io/trait.AsyncWrite.html). Well, once it is updated to that, I can integrate this crate then 👍

**Comment by gkelly** [comment]
It looks like the plan might be to drop tokio support from this crate and have people depend on the async_compression crate for that instead: https://github.com/rust-lang/flate2-rs/pull/214
