### ISSUE TITLE
How to decompress files?

### ISSUE THREAD

**Issue by 834772509** [rust-lang/flate2-rs#275]
I found examples of compressed files in the examples, but no examples of decompressed files.
I've tried to write code for decompressing files, but the prompt is "error: decompresserror (decompresserrorinner {needs}_ Dictionary: none})} ", can you provide an example of decompressing a file?

**Comment by alexcrichton** [comment]
Decompression uses the "decoder" family of types, and their usage should be included in the examples of this repository (all the usage is very similar).

If you're getting an error you may not be using the right type of decoder or you might be using a different format this crate doesn't support.
