### ISSUE TITLE
Examples that don't just read_to_string

### ISSUE THREAD

**Issue by SenojLuap** [rust-lang/flate2-rs#294]
I have no idea how common the `read_to_string()` use case is, but I've been struggling with errors attempt to decompress to a file, and wouldn't mind seeing some examples of that.

**Comment by MichaelMcDonnell** [comment]
@SenojLuap, I've created an [example that decompresses a file](https://github.com/MichaelMcDonnell/flate2-rs/blob/decompress_file/examples/decompress_file.rs). Is that what you were looking for?

**Comment by SenojLuap** [comment]
Oof. Had to remember what it was I was working on a year ago 😢 
But, I'm pretty sure this is close to the scenario I was interested in, yes.

Thanks!
