### ISSUE TITLE
[Enhancement] Add support for zstd

### ISSUE THREAD

**Issue by kallisti5** [rust-lang/flate2-rs#298]
zstd is becoming a popular standard for compression, any plans to add it?

 https://facebook.github.io/zstd/

**Comment by joshtriplett** [comment]
@kallisti5 flate2 is specifically a crate for the DEFLATE/zlib/gzip format. I don't think it makes sense to add zstd support to it. There are already multiple crates for zstd, including https://crates.io/crates/zstd and https://github.com/Nemo157/async-compression/ .
