### ISSUE TITLE
error: failed to verify the checksum of `flate2 v1.0.24`

### ISSUE THREAD

**Issue by mstumpf585** [rust-lang/flate2-rs#319]
Trying to build a project on my work PC that forced me to set my check-revoke = false due to IT sniffing our HTTPS packages with a custom SSL certificate. After doing this I keep getting a checksum failure for flate2 v1.0.24. I tried downgrading to 1.0.20 but got the same issue. Is there a way to bypass the checksum or figure out why flate2's checksum is failing when other packages aren't? I tried doing this on a windows 10 machine and then once again on a docker image based off of ubuntu and got the same error each time. Oddly enough on my non-work PC running windows 11 flate2 gets downloaded and everything is happy.

**Comment by marklaptenok** [comment]
I have the same error in the same context ($env:CARGO_HTTP_CHECK_REVOKE = 'false'). Are there any updates on the issue?

**Comment by JohnTitor** [comment]
Could someone provide steps to reproduce the issue? The docker image @mstumpf585 used might be helpful to debug.

**Comment by mstumpf585** [comment]
So a colleague of mine was able to figure out what was wrong. Apparently Cisco blocked the download which would lead to a checksum failure. We had to raise an issues with IT and we double checked the crate for vulnerabilities and we unblocked it. @JeroenKnoops please feel free to add to this if you have any other information.

**Comment by JeroenKnoops** [comment]
Indeed. The crate was unrightfully marked as malware. Now it's unblocked in Cisco Umbrella.

**Comment by mstumpf585** [comment]
I guess I'll close this out since it was an issue on our end.
