### ISSUE TITLE
New crates.io release

### ISSUE THREAD

**Issue by fintelia** [rust-lang/flate2-rs#321]
This would be useful because the current crates.io version depends on miniz_oxide 0.6 while the git main branch has since upgraded to 0.6.

**Comment by thomcc** [comment]
Might be blocked on https://github.com/rust-lang/team/pull/879.

**Comment by rylev** [comment]
FYI: crates.io crate ownership is not controlled by the team repo.

**Comment by FreezyLemon** [comment]
Any update on this?

**Comment by FreezyLemon** [comment]
I dislike being pushy, but is there anything blocking this? The crate has a high download volume (~500k downloads per _week_) and I think removing duplicate dependencies (a lot of dependent crates have updated to miniz_oxide ^0.6 while this crate will additionally pull ^0.5) is a worthwhile change.

**Comment by thomcc** [comment]
There's some permissions issues that complicate cutting the release but it should be done in the near future (a day or so, https://github.com/rust-lang/flate2-rs/pull/327).

**Comment by FreezyLemon** [comment]
Okay, thanks for the fast response!

**Comment by thomcc** [comment]
A release has been published on crates.io: https://crates.io/crates/flate2/1.0.25.

I'll put up a github release with release notes tomorrow or so (holiday).

**Comment by JohnTitor** [comment]
I've made a GitHub Release in case Thom forgot about it: https://github.com/rust-lang/flate2-rs/releases/tag/1.0.25
@thomcc Feel free to edit the release notes if you'd like!

Closing as done

**Comment by thomcc** [comment]
Sorry, thank you.
