### ISSUE TITLE
Request: new release to have `miniz_oxide` 0.7 dependency

### ISSUE THREAD

**Issue by poliorcetics** [rust-lang/flate2-rs#340]
With https://github.com/rust-lang/flate2-rs/pull/335, `minz_oxide` was updated to 0.7

Could we have a release of `flate2` with this included ?

**Comment by JohnTitor** [comment]
Submitted #341, the release will happen when Mark has some time to release.

**Comment by poliorcetics** [comment]
Thanks!

**Comment by JakubOnderka** [comment]
Please also include new version of https://github.com/rust-lang/libz-sys dependency in new release.

**Comment by JohnTitor** [comment]
@JakubOnderka Note that this repo is flate2-rs, you need libz-sys v1.1.9 first. I've submitted https://github.com/rust-lang/libz-sys/pull/117 anyway.
