### ISSUE TITLE
Error on compiling flate2 on rust 1.57.0

### ISSUE THREAD

**Issue by vladimirfomene** [rust-lang/flate2-rs#370]
Compiling flate2 v1.0.27
error[E0658]: deriving `Default` on enums is experimental
  --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.27/src/gz/mod.rs:90:17
   |
90 | #[derive(Debug, Default)]
   |                 ^^^^^^^
   |
   = note: see issue #86985 <https://github.com/rust-lang/rust/issues/86985> for more information
   = note: this error originates in the derive macro `Default` (in Nightly builds, run with -Z macro-backtrace for more info)

**Comment by jongiddy** [comment]
flate2 v1.0.28 can be compiled with older versions of Rust going back to 1.54.
