### ISSUE TITLE
flate2::bufread::GzDecoder doesn't impl BufRead?

### ISSUE THREAD

**Issue by georeth** [rust-lang/flate2-rs#374]
The document says:

https://github.com/rust-lang/flate2-rs/blob/f285e9abac98aa4f0a15d2e79993a261f166056c/src/gz/bufread.rs#L22-L24

but `flate2::bufread::GzDecoder` only implement `Read`.

https://github.com/rust-lang/flate2-rs/blob/f285e9abac98aa4f0a15d2e79993a261f166056c/src/gz/bufread.rs#L281

`BufRead` interface is not implemented and exposed.

**Comment by georeth** [comment]
Other decoders in `bufread` mod **consumes** a `BufRead`.

https://github.com/rust-lang/flate2-rs/blob/f285e9abac98aa4f0a15d2e79993a261f166056c/src/deflate/bufread.rs#L10

I think `GzDecoder`'s documentation should be fixed.

**Comment by Byron** [comment]
Thanks a lot for pointing out this error. Would you like to become a contributor? I'd appreciate your help. Thanks for your consideration.

**Comment by georeth** [comment]
Sure. I will create a pull request to fix the doc when I'm back at a keyboard.
