### ISSUE TITLE
unknown return code: -4

### ISSUE THREAD

**Issue by prz23** [rust-lang/flate2-rs#411]
![image](https://github.com/rust-lang/flate2-rs/assets/29329767/f31b97a2-7474-44dc-8528-6c3474533c34)

**Comment by prz23** [comment]
![image](https://github.com/rust-lang/flate2-rs/assets/29329767/fad20693-cc90-44c5-ac1f-96d2bd38e951)


The case with -4 will cause an error,  and data is transient..

**Comment by Byron** [comment]
Indeed, the code triggered [is here](https://github.com/Byron/flate2-rs/blob/5ce4154d2b50dfc4b82eaea772fed82c616b501f/src/ffi/c.rs#L271) and it seems like `-4` refers to `Z_MEM_ERROR`.

I think it that should be handled as well and cause an error instead.

Would you like to contribute this as PR? I'd do it too but can't merge my own PRs, so having a base-PR would be helpful to get a fix more quickly.
