### ISSUE TITLE
No git tag/release for 1.0.31

### ISSUE THREAD

**Issue by mmm-8192** [rust-lang/flate2-rs#417]
The 1.0.31 release doesn't have a git tag or release page (making it slightly difficult to see what has changed)
It seems that the only non-comment/doc change (if I am comparing correctly) is the update of the `libz-rs-sys` library from 0.1.1 to 0.2.1

**Comment by Byron** [comment]
I am aware and am trying to get the linked PR to be approved so it can be merged - I cannot self-approve unfortunately.

**Comment by Byron** [comment]
Thanks for the heads-up, indeed the new tag wasn't pushed. For good measure, I also created one with the previous naming scheme.

```
❯ gp --tags
Enumerating objects: 1, done.
Counting objects: 100% (1/1), done.
Writing objects: 100% (1/1), 646 bytes | 646.00 KiB/s, done.
Total 1 (delta 0), reused 0 (delta 0), pack-reused 0
To https://github.com/rust-lang/flate2-rs
 * [new tag]         1.0.31 -> 1.0.31
 * [new tag]         v1.0.31 -> v1.0.31
```
