### ISSUE TITLE
Allow re-use of buffers provided to `new_with_buf`

### ISSUE THREAD

**Issue by marshallpierce** [rust-lang/flate2-rs#71]
I'm working on using flate2 to add support for the deflate-based serialization formats for [HdrHistogram](http://hdrhistogram.org/) to this [Rust implementation](https://github.com/jonhoo/hdrsample). However, some parts of the `flate2::read::DeflateDecoder` and `flate2::write::DeflateEncoder` API are awkward for my use case.

The [`Deserializer`](https://github.com/jonhoo/hdrsample/blob/master/src/serialization/deserializer.rs) struct in that library exists to let the user amortize buffer allocation costs across all deserializations (no heap allocation once steady state has been achieved), with similar goals for the serialization equivalent. The struct itself is not generic, but it has a generic `deserialize` method:

```
pub fn deserialize<T: Counter, R: Read>(&mut self, reader: &mut R)
                                            -> Result<Histogram<T>, DeserializeError> 
```

My understanding of the `DeflateDecoder` API leads me towards a few options, none of which is particularly attractive:

1. Make `Deserializer` follow the same "consume the writer, then return it later" structure. This means `Deserializer` must itself be generified on `R: Read`, must always wrap a `Read` (which means it can't be created during startup before there might be anything to read from), etc.
2. Make a new `DeflateDecoder` for each deserialization. This spoils my hope to avoid heap allocation, but allows me to keep the `Deserializer` API the way it is.
3. Require `BufRead` instead of `Read`. That would let me create a `flate2::bufread::DeflateDecoder` for each deserialization, but it pushes buffer management to the user: now they have to figure out how to re-use buffers across `Read`s, assuming they put forth the effort to avoid the heap allocation. It doesn't look like `std::io::BufReader` will let you reclaim its buffer space, for instance. On the other hand, perhaps it's likely that in practice people will have a `BufRead` already?
4. Copy-and-paste `flate2::bufreader::BufReader` and modify it to take (and release) a `Box<[u8]>` (or maybe just a `&mut [u8]`?) and use that with `flate2::bufread::DeflateDecoder`. 

`DeflateDecoder::new_with_buf` almost makes option 2 above feasible, but I can't get the buffer back out again to use it again later. So, if there was a way to either not require that the Vec be consumed (preferable, as I wouldn't have to shuffle the Vec in and out of the `Deserializer` struct), or at least offer a way to consume the `DeflateDecoder` to get the `Vec` back out (like `into_inner()` but for the buffer), that would let me keep the `Deserializer` API I prefer.

Surely I can't be the only one who wants this form of re-use... What do you think? Am I missing something?

**Comment by alexcrichton** [comment]
Note that for maximal flexibility you can use the [`Decompress`](https://docs.rs/flate2/0.2.17/flate2/struct.Decompress.html) type to have complete control over buffer management it's just sometimes a pain to use. Otherwise though yeah seems plausible to be able to extract the buffer!

**Comment by marshallpierce** [comment]
Ah, I'll look into Decompress. Thanks for the tip.

**Comment by joshtriplett** [comment]
I'm going to close this for now. I think that it's possible to do what was requested using `Decompress`, and it's also possible to reuse (some of the) buffers with flate2 and the `reset` methods.
